# Site settings
name: Riccardo Calligaro
title: Riccardo Calligaro | Mobile App Developer
description:  Design-minded mobile app developer focused on building beautiful interfaces and experiences
url: https://riccardocalligaro.github.io/
baseurl: ''
email: riccardocalligaro@gmail.com
cover: https://riccardocalligaro.github.io/img/og.png
logo: https://riccardocalligaro.github.io/img/emojis/phone.png
resume: https://riccardocalligaro.github.io/resume.pdf
social:
  - title: email
    url: mailto:riccardocalligaro@gmail.com
  - title: github
    url: https://github.com/riccardocalligaro

permalink: projects/:title/

# Build settings
markdown: kramdown


exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

